/*
 * Copyright (C) 2018
 * Área Académica de Ingeniería en Computadoras, ITCR, Costa Rica
 *
 * This file is part of the numerical analysis lecture CE3102 at TEC
 *
 * Automatically generated by CMake using the template cmake/AnpiConfig.hpp.in
 */

#define SILENT_ENABLE_SIMD
/* #undef _ENABLE_OpenMP */
#define SILENT_DATA_PATH "/home/roberto/Documents/github/silent-filter/data"
